config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:new]
  root to: 'tops#index'
  resources :posts
  resources :movies
  resources :graphs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, :weight, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :nowweight, :targetweight])
  end

  def after_sign_up_path_for(resource)
    user_path(user.id)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_post, :set_user

  def index
    # 20200209 追記

    @graphsdays = @user.posts.order(created_at: "DESC").limit(5).reverse
    # @graphsdays = [2020-02-04,2020-02-04,2020-02-04,2020-02-04,2020-02-04]

    @dayline = Array.new
    @graphsdays.each do |graphday|
      
      @dayline.push(graphday.created_at.strftime('%m/%d').to_s)
      # @dayline.push(graphday)
    
    end
    # @arr = [20200209,20200210,20200211,20200212,20200213]
    # @post = Post.find(params[:post_id])
    # @arr = @post.created_at
    # @arr_json = @arr.to_json.html_safe
    # 20200209 追記

    @graphweights = Post.order(created_at: "DESC").limit(5).reverse
    # @graphweights = [59.5,59,57.5,50,59.5]

    @weightline = Array.new
    @graphweights.each do |graphweight|
    
      @weightline.push(graphweight.weight)
      # @weightline.push(graphweight)
    
    end
    sum = 0
    gon.bardata = []
    gon.linedata = []
    7.times do |i|
      data = rand(100.0)
      gon.bardata << data
      sum = sum + data
      gon.linedata << sum
    end
  end

  def set_post
    # posts = Post.find(user_id: current_user.id)
    @posts = Post.all
  end

  def set_user
    # @user = User.find(params[:user_id])
    @user = User.find(current_user.id)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.json
      end
    else
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :weight).merge(user_id: current_user.id)
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(7)
    # @aaa = @posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/graphs/index.html.haml
-# %canvas#spotsChart{:height => "200", :width => "200"}
:javascript
  var graphdays = #{raw @dayline}, graphweights = #{raw @weightline}

-# :javascript
-#   draw_graph();


-# %input{:name => "arr_json", :type => "hidden", :value => @a}
-# %input.arr_json{:name => "arr_json", :type => "hidden", :value => @arr}/
%canvas#myLine2Chart{:height => "400", :width => "800"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    -# %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    %title DIETRECORD
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = Gon::Base.render_data
    = javascript_include_tag 'application'
  %body
    = yield

app/views/movies/index.html.haml
.movie_contents
  .movie_content
    Training movies
  -# .movie_box
  -#   %p.lupin ダイエット用動画集
  .movies
    .movie1
      初級編
      %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/PxDVpRv6SqE", :width => "560"}
    .movie2
      中級編
      %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/V7SF9Vwb1aQ", :width => "560"}
    .movie3
      上級編
      %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/z8JJIc5H9og", :width => "560"}

  .header__title
    = link_to "DIET-RECORD", user_path(current_user.id), class: "header__title--text"

app/views/posts/_header.html.haml
.index-header
  .header__title
    = link_to "DIET-RECORD", root_path, class: "header__title--text"
  .header__right
    -# = link_to current_user.nickname, user_path(current_user), class: "header__right--btn"
    = link_to new_post_path, class: "btn btn-danger" do
      新規投稿
    = link_to destroy_user_session_path, method: :delete, class: "btn btn-danger" do
      ログアウト
  .header__right2
    = link_to movies_path, class: "btn btn-danger" do
      おすすめ動画
    = link_to graphs_path, class: "btn btn-danger" do
      グラフで見る

app/views/posts/_post.html.haml
.content
  .content__left
    .content__left--image
      -# = post.weight - @aaa
  .content__right
    .content__right__top
      = link_to post.title, post_path(post.id), class: "content__right__top--title"
    .content__right__bottom
      .content__right__bottom--userName
        = link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn"
      .content__right__bottom--date
        = post.created_at

app/views/posts/edit.html.haml
= render partial: 'header'
.contents
  .content__title
    投稿の編集
  .content__form
  = form_with model: @post, class: :form, local: true do |form|
    = form.text_field :weight, placeholder: :今日の体重, class:"form-control"
    .2
    = form.text_field :title, placeholder: :タイトル, class:"form-control"
    = form.text_area :content, placeholder: :本文, class:"form-control"
    = form.submit '変更する', class: :form__btn

app/views/posts/index.html.haml
= render partial: 'header'

- @posts.each do |post|
  = render partial: "post", locals: { post: post }

app/views/posts/new.html.haml
= render partial: 'header'
.contents
  .content__title
    ☆今日の成果☆
  .content__form
  = form_with model: @post, class: :form, id:"new_post", local: true  do |form|
    .form-group
      = form.text_field :weight, placeholder: :今日の体重, class:"form-control"
    .2
      = form.text_field :title, placeholder: :タイトル, class:"form-control"
      = form.text_area :content, placeholder: :本文, class:"form-control"
      = form.submit '報告する', class:"form__btn"
      

app/views/posts/show.html.haml
= render partial: 'header'
.contents
  .postTitle
    = @post.title
  .postDate
    = @post.created_at
  .postWeight_content
    ☆測定結果☆
  .postWeight_box
    .postWeight
      = "#{@post.weight}kg"
  .postText
    = simple_format @post.content
  .postAuthor
  - if current_user.id == @post.user_id
    .postManage
      = link_to "編集", edit_post_path(@post.id), class: "postManage__edit"
      = link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete"

app/views/tops/index.html.haml
.wrraper
  .top__header
    .top__header2
      .top__header_content
        DIET-RECORD

  .top__main
    .top__signup_btn_box
      =link_to "Sign Up", "/users/sign_up", class:"top__signup_btn"
    .top__signin_btn_box
      =link_to "Sign In", "/users/sign_in", class:"top__signin_btn"
         

app/views/users/show.html.haml
= render partial: 'posts/header'
.contents
  .postTitle1
    = @user.nickname
    さんの体重記録
  - @posts.each do |post|
    = render partial: "posts/post", locals: { post: post }
  .contents__page
  = paginate(@posts)